name: Daily API Key Rotation Job

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  fetch-company-names:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install requests

      - name: Run API Key Rotation Script
        env:
          API_KEYS: ${{ secrets.API_KEYS }}
          CSE_CONFIG: ${{ secrets.CSE_CONFIG }}
        run: python script.py

      - name: Stash Unstaged Changes (if any)
        run: |
          git diff --quiet || git stash --include-untracked

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Pull the latest changes from the remote
          git pull origin main --rebase

          # Check if there are any changes to commit
          git diff --quiet || (
            git add websites.json
            git commit -m "Auto-update websites.json"
            git push origin main
          )
